version: '3'
services:
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
  web:
    stdin_open: true
    tty: true
    build: .
    # command: tail -f /dev/null
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/sample_app
      - bundle:/usr/local/bundle
      - /sample_app/tmp
      - ./tmp/screenshots:/sample_app/tmp/screenshots
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - "SELENIUM_DRIVER_URL=http://selenium_chrome:4444/wd/hub"
      

  selenium_chrome:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none  

volumes:
  bundle:
    driver: local
  db:
    driver: local